### ISSUE TITLE
ResetDatabaseCommand broken

### ISSUE THREAD

**Issue by vpassama** [CanalTP/SamCoreBundle#52]
Hi !

Even if you don't use it anymore (I think), the commit https://github.com/CanalTP/SamEcoreApplicationManagerBundle/commit/fd76977c8bc77a589ff5146ad3404b889d5da7b4 broke something in the ResetCommandDatabase as it still uses the function getBridgeApplicationBundles renamed to getApplicationBundles.

**Comment by dvdn** [comment]
Hi,
resolved few months later... 2 years ago :sweat_smile: 
see PR https://github.com/CanalTP/SamCoreBundle/pull/58
